function(find_lib_packages)
    find_package(cpt-lib CONFIG REQUIRED)
    find_package(spdlog CONFIG REQUIRED)
    find_package(tl-optional CONFIG REQUIRED)
    find_package(raylib CONFIG REQUIRED)
endfunction()